# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
language: c
env:
  # Build and test against the master and devel branches of Nim
  - BRANCH=master
  - BRANCH=devel
compiler:
  # Build and test using both gcc and clang
  - gcc
  - clang
matrix:
  allow_failures:
    # Ignore failures when building against the devel Nim branch
    - env: BRANCH=devel
  fast_finish: true
install:
  - |
    # We want a new GCC 4.8 instead of 4.6.x
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update -qq
    if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    # Install Nim
    if [ ! -x nim-$BRANCH/bin/nim ]; then
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
      cd nim-$BRANCH
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      cd nim-$BRANCH
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    cd ..
    # So we can see nim compiler
    export PATH=$PWD/nim-$BRANCH/bin:$PATH
    export PATH=$HOME/.nimble/bin:$PATH
    # Install nimble
    if [ ! -x $HOME/.nimble/bin/nimble ]; then
      git clone --depth 1 https://github.com/nim-lang/nimble.git
      cd nimble
      nim c -r src/nimble install
      cd ..
    else
      nimble install nimble  
    fi
before_script:
    - cd $TRAVIS_BUILD_DIR
    - pwd && ls
    - nimble refresh
script:
    # Let nimble get dependencies
    - nimble c src/nitest
    # Test
    - cd src && ./test.sh
    # Optional: build docs.
    # nim doc --docSeeSrcUrl:https://github.com/AUTHOR/MYPROJECT/blob/master --project MYFILE.nim
cache:
  directories:
    - nim-master
    - nim-devel
branches:
  except:
    - gh-pages
